from setuptools import setup, find_packages

setup(
    name='Pdf_Word_Count',  # This should match the name you want for your package
    version='0.1',  # Update the version number as appropriate
    packages=find_packages(),
    # Include additional fields as necessary:
    description='get the count of words in a pdf file',  # Optional
    author='Aditya Sharma', #https://github.com/adityashrm21/Pdf-Word-Count/commits?author=adityashrm21  # Optional
    author_email='community',  # Optional
    url='', #'https://github.com/adityashrm21/Pdf-Word-Count',  # Optional
    license='MIT',  # Optional, specify the license as appropriate
    install_requires=[
        # List any dependencies that pypdf needs, for example:
        # see here: https://github.com/py-pdf/pypdf/blob/main/requirements/dev.txt
        # This file is autogenerated by pip-compile with python 3.7
        # To update, run:
        #
        #    pip-compile requirements/dev.in
        #
        'PyPDF2==3.0',
        # try installing both package
        'pypdf==3.1.0'
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',  # Update as appropriate
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
    ],
    python_requires='>=3.7',  # Specify which Python versions you support
)
